### ISSUE TITLE
Support custom quality standards

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#200]
# The Problem

The need to find a concept/strategy for how the default quality standards (defined by a schema) can be extended or replaced. 
Therefore three topics need to be discussed:

- How should a custom standard be defined?
- How is the usage of a custom standard reflected in a weldx file?
- How can it be integrated into the current Python API? 

The solutions to the first 2 questions must be fully API and system agnostic.

# Proposed solutions

### Proposal 1: Manifest file

The idea is based on the way how the asdf maintainers want to separate the transform schemas from the main repository (see [this link](https://github.com/asdf-format/asdf-transform-schemas) -> `resources/stsci.edu/`). 
Each standard will be defined by a versioned manifest file. 
This file contains some metadata about the standard itself. 
It also contains a relative path to the root directory with all the schema files and the mappings between tags and schemas that should be updated.
An example manifest file might look like this:

- add schema extension mechanism

~~~ yaml
id: $ID_OF_THE_STANDARD # including the version number
description: |
   explain what this standard is assuring
compatible_weldx_versions: # optionally use a required version or min/max version
- 1.0.0
- 1.0.3

schema_directory: $RELATIVE_PATH_TO_SCHEMA_ROOT_DIRECTORY # relative to manifest file

mappings:
- ["tag:weldx.bam.de:weldx/core/time_series-1.0.0", "schemas/new_time_series_schema.yaml"]
- ["tag:weldx.bam.de:weldx/core/mathematical_expression-1.0.0", "schemas/new_mathematical_expression_schema.yaml"]
~~~

We might also consider a schema extension syntax.
Some schemas are pretty long like the [time series schema](https://github.com/BAMWelDX/weldx/blob/master/weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml).
If only some minor changes should be applied, one could express it like this in the manifest_file:

~~~ yaml
extend_schemas:
- tag: "tag:weldx.bam.de:weldx/core/transformations/local_coordinate_system-1.0.0"
  replace: 
  - wx_shape:
      (coordinates):
        data: [3] # only static coordinates
  - additionalProperties: true # allow additional properties
  add:
  - required: [coordinates] # add some requirements
~~~

Here is the file that would be modified if you like to compare it: [click](https://github.com/BAMWelDX/weldx/blob/master/weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-1.0.0.yaml)

As proposed by @CagtayFabry, a quality standard should ideally be published in its own GitHub repository.
The file structure should be chosen/prescribed in a way that the repository can be easily installed by resource managers like pip.

### Proposal 1: Add an entry to the file header
An easy solution (if the asdf API supports it), would be to add a `standard` field to the files history section.
This might look as follows:

~~~ yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.8.0.dev107+g8ccee8b}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.8.0.dev107+g8ccee8b}
  standards:
  - $WELDX_STANDARD_META_TAG
    repository: $WELDX_STANDARD_REPOSITORY_TAG
      provider: GitHub
      owner: weldx
      repository: weldx
      brach: master
      version: 0.0.1 # obtionally use a commit hash
~~~

The nice thing here would be that the information where the standard can be found would be included in the file.
Also, as long as the new standard only applies stricter boundaries and files validated against it will also pass the weldx default validation, the corresponding file can be read without the need to install the standard. 
(maybe the manifest file should get a corresponding boolean field like `required_to_read`)
The drawback is that it is not clear which object is validated against which standard without taking a look into the files of the standard.
This might get really tricky if multiple standards are used.
(What if both define changes to the same object?)

### Proposal 2: Retag objects
Another method would be to include the standard into the tag of the objects that use it.
The issue that the file couldn't be read without the standard being installed (different tag) might be circumvented by adding the standard as a suffix to the original tag:

~~~
tag:weldx.bam.de:weldx/core/transformations/local_coordinate_system-1.0.0-$my_standard-1.2.3
~~~
If the tag can't be found, the suffix is removed from the tag which results in using the default schema.

Using this approach does tell us which objects use which standard but without further information, it is not known where the standard is defined.
 
### Proposal 3: Add `standard` field to objects
This is quite similar to proposal 2 with the only difference that the standard is stored as an additional field instead of being attached to the tag.
However, this would require that all schemas provide a corresponding property or allow additional properties.
This might be a little bit annoying.

### Proposal 4: Turn on the mixer!
The previously described methods are not mutually exclusive.
So one can mix them if necessary

# How can it be integrated into the current Python API?

### Modifying tag to schema mapping

Depending on the ASDF version the tag to schema mapping is done differently. 
Before version `2.8.0` the mapping was quite static and defined by the extension.
To be more specific, by the functions `tag_mapping` and `url_mapping`.
However, we won't discuss how to use them with a new standard since we are targeting version `2.8.0` which makes it pretty easy.
In version `2.8.0` one can simply use the function:

~~~ python
asdf.get_config().add_resource_mapping(mappings)
~~~

The mapping must be a dictionary with the object id as the key and the content of the schema file as the value.
So we could do something like this (pseudo python code):

~~~ python
mappings = {}

for cls in my_extension.types:
   key = "http\\id_of_original_schema"
   schema_path = "path_to_new_schema.yaml"
   schema = generic_io.get_file(schema_path).read().decode('utf-8')
   mappings[key]=schema

asdf.get_config().add_resource_mapping(mappings)
~~~

### Modifying tags

If we want to apply a custom schema together with a new tag for an existing object (like in the section "Proposal 2: Retag objects") it is not enough to remap the used schema.
This would cause a tag validation error.
We need to retag the corresponding python objects too:

~~~ python
for cls in my_extension.types:
    cls.yaml_tag = "new_tag"
~~~

### Proposal 1: WeldX configuration manager

In the upcoming asdf version 2.8.0 a global configuration manager was introduced.
A similar approach would probably make sense for weldx standards.
Applying a standard would then be as easy as follows:

~~~ python
weldx.config().apply_standard("$PATH_TO_MANIFEST_FILE")
~~~

### Proposal 2: Standards as extensions

We could also define some generic extension that can get a generic extension that loads a manifest file and applies it when its added to an `asdf_file` instance.
However, this would be more complicated for the user than the previous approach and I am also not sure if such an extension can be "installed".

### Additional note

I would also suggest that we add the possibility to pass one or more manifest files to the `__init__` method of the weldx extension.
If it is not installed on a system, just included, an instance has to be created anyway to pass it to asdf.

**Comment by CagtayFabry** [comment]
Thanks for the writeup @vhirtham 🚀 

Some initials thoughts and notes:

## Manifest
### regarding the manifest file:
- Would we not list `URI` - `filename` mapping here instead of `tag` - `filename` ? There is no mention here of the `URI`.
  Imo the `tag` - `URI` mapping should live in the Python world (our `WeldxExtension`) and the `URI` - `filename` mapping would be part of the Manifest (the `asdf` world).
 Of course this changes a bit if we decide to somehow change the tags
- I would have expected the manifest file to look closer to the asdf reference, does the format not suit us?
  I think the main (only?) difference in our approach is that the asdf manifest only adds schemas but we override existing schemas. The way `asdf.get_config().add_resource_mapping(mappings)` is implemented I think the asdf approach might work for us.
- I like having some info like `compatible_weldx_versions`, but not sure how best to handle this. Maybe this is not needed because all the individual files are versioned? So the compatible version is reflected in the URI mapping.
- instead of explicitly defining `schema_directory` I would prefer a clear template of how to name and structure the git repository and go from there

### schema extension syntax
- I like the idea, this functionality would be nice to have (even aside from this issue).
- However, I also like having complete YAML files to read and also render in the docs. Each quality standard should have their own readthedocs website for easy viewing and rendering with `sphinx-asdf`

## How is the usage of a custom standard reflected in a weldx file?
### history entry
- we should definitly do this, might be easy [`AsdfFile.add_history_entry`](https://github.com/asdf-format/asdf/blob/8ccee8b17a053d6e33ebca81a4ed3f3c3569aee1/asdf/asdf.py#L1421)
- I think the "final" quality standards should be published and installed via pip/conda (we should also maintain a metapackage that collects and installs all relevant standards). I think cloning via GitHub and pip install or similar is too complex/confusing

### Retag objects
- I like appending the schema info to to end of the tag because it does keep the original tag (and I see a realistic chance of parsing this)
- **However** I still have a really bad feeling about changing tags. Here is why:
  In my opinion, tags should only be used as a bridge to the Python world to associate some elements of a ASDF file with a certain class. So for me everything that somehow does anything with tags should also provide the python implementation. This is exactly what a `AsdfExtension` does.
  The bridge here for me would be a another Extension in addition the the `WeldxExtension` that overrides the `class` - `tag` by associating existing weldx classes with new tags and might as well add or replace its own schema definitions.

**Comment by vhirtham** [comment]
> Would we not list URI - filename mapping here instead of tag - filename ? 
We can also use the URI. I think it doesn't matter that much. Both are included in a schema and the extension knows how to map between them. However, I am still not really sure about the long term purpose of having both since they contain the same information (atm)

> I would have expected the manifest file to look closer to the asdf reference, does the format not suit us?

Taking [this example](https://github.com/asdf-format/asdf-transform-schemas/blob/master/resources/stsci.edu/manifests/transform-1.5.0.yaml), I think it contains a lot of redundant information that can be found in the schemas too. Therefore it looks extremely cluttered to me. On the other hand, it doesn't provide any (direct) information where the schemas are located. 
In my opinion, the manifest file should be like a table of content in a book plus its summary. It should tell me what its purpose is and give me a brief overview of its content and where it can be found.

> I like having some info like compatible_weldx_versions, but not sure how best to handle this. Maybe this is not needed because all the individual files are versioned? So the compatible version is reflected in the URI mapping.

Well, not sure if we actually want to "handle" it and you are right that the information is implicitly contained in the replaced schemas, but stressing my idea of the manifest file's purpose, it should simply tell the user directly what he needs. 

> instead of explicitly defining schema_directory I would prefer a clear template of how to name and structure the git repository and go from there

that is an option

> However, I also like having complete YAML files to read and also render in the docs. Each quality standard should have their own readthedocs website for easy viewing and rendering with sphinx-asdf

Agreed on the documentation part, however, that is nothing that can't be done with a short python script (`generate_full_schema_files.py` ;p ). I would prefer to have this option because it is much easier to see what the standard is doing differently in very complex files. If too much needs to be changed, one can still write a new schema.

> Retag objects

also not sure about retagging, just wanted to list our options
