### ISSUE TITLE
Use pyfilesystem

### ISSUE THREAD

**Issue by vhirtham** [BAMWelDX/weldx#208]
While thinking about how to proceed with the quality standard tutorial I found this interesting python package:

https://docs.pyfilesystem.org/en/latest/introduction.html

As the name suggests, it's about file systems and you might wonder what its advantages are over the already existing `os` and `pathlib` packages. There are probably a lot more but for me, the [builtin filesystems](https://docs.pyfilesystem.org/en/latest/reference/zipfs.html) were the selling point. You can read/write content directly from zip or tar files as you can read from/write to your hard drive by simply swapping the filesystem object. So as an example you can also download and use our quality standards in an archive without the need to unpack them. But the specific feature that lead me to this package is the virtual file system. It allows me to create and use a whole virtual quality standard file structure in the tutorial without the need to actually create the files on the disk. I am currently modifying the quality standard implementations to support it and so far, everything works as expected without making things more complicated. I think this is a really nice package. So what do you think?

**Additional note:**
As mentioned in their [Why use PyFilesystem](https://docs.pyfilesystem.org/en/latest/guide.html#why-use-pyfilesystem) section, the virtual file system is also a nice feature for tests that need external files

**Comment by CagtayFabry** [comment]
the virtual filesystem feature sounds really good for complex test cases like this 👍 
We will probably have to discuss how to approach testing soon

Since this seems like an API backend design the user should not really have to worry about it imo, I would prefer the tutorial not to go into too much depth in this regard.

I am not sure how using quality standard (QS) repo zip files would work and if that is an approach we should advise the user to take. Would there be no `pip install` in this scenario? How to propagate the version in this case?

I am not sure if there are benefits over `pip install git+https://github.com/whatever` or plain `pip install -e ~/repo`

best you give me an overview and we discuss the tutorial contents on monday @vhirtham :)

**Comment by vhirtham** [comment]
It's now part of the requirements. -> [PR #215](https://github.com/BAMWelDX/weldx/pull/215)
