### ISSUE TITLE
consider unifying building/testing in conda recipe (in favour of environment.yml)

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#240]
This has the advantage of simplifying the build process on CI, as one only invokes conda-build (or boa) to run build and testing (even in several variants, e.g. NumPy/Python versions) in one shot.
However I like the minimal conda-recipe as it is right now, but it lets us repeat these build/test steps on every setup.

I think environment.yaml is mainly used for reproducible env creation on users (and developers) side.

**Comment by marscher** [comment]
A conda recipe (which is passed into conda-build or boa) is also used on conda-forge to ship the package. So since this work has to be done anyway, I suggest we switch to conda-building within CI sooner than later. A recipe basically defines the package name, its version, and build and runtime dependencies. It can also be defined how a package is tested, e.g. install additional packages during test phase.

@CagtayFabry Is the environment.yaml solution meant for a quick developer install, or what is the overall intention here?

**Comment by CagtayFabry** [comment]
current list of dependencies/environments:

- actual code/package dependencies are listed in `setup.py`
all `pytest` actions are based on this running `pip install -e` which seems faster than `conda`/`mamba`
- `environment.yml` is only used for quick user/dev environment setup with basic tools etc.
- `.binder/environment.yml` binder environment with a fixed set of working jupyterlablab/node/ipympl/matplotlib versions (should be updated to match jupyterlab 3 soon)
- `doc/rtd_environment.yml` environment used for building docs on RTD (should also run `pip install -e` during build)
- `conda.recipe/build_env.yml` conda build tools

it's a little convoluted since everything is still in one repo. In the future I suggest breaking parts into different packages like core/tools/widgets etc. to streamline dependencies and testing

**Comment by marscher** [comment]
pip is indeed much faster than mamba, so we should prefer it, whenever possible.

About splitting up into small modules... from my experience this leads to lots of maintenance overhead hindering fast development. This is mainly caused  by (manual) dependency tracking of the involved modules and so the split up should be done once we arrived at a stable state.

**Comment by CagtayFabry** [comment]
I think we can remove the `environment.yml` file at some point soon so we don't have to keep track

right now the following should give a nice well rounded environment including docs build etc.
```
mamba env create -n weldx python=3.8 pip
mamba install -n weldx weldx -c conda-forge --only-deps
pip install -e .
mamba env update -n weldx --file ./doc/rtd_environment.yml
```

just need some file to store the test requirements

**Comment by CagtayFabry** [comment]
Is this still relevant after #299 #319 ?
Maybe we should move `environment.yml` ?

**Comment by marscher** [comment]
I think we decided to move this to a directory "devtools", right?
