### ISSUE TITLE
Test architecture internal dependencies

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx#334]
Since we started to run our tests in parallel, we have to ensure, that the order of execution is independent. For instance a test class
has a static attribute, which is being modified by the individual test methods.
``` python
class TestFoo:
    complex_structure = {}

    def test_add_attr1(self):
        self.complex_structure['a'] = 1
        assert len(self.complex_structure) == 1

    def test_add_attr2(self):
        self.complex_structure['b'] = 1
        assert len(self.complex_structure) == 2
```
Here we see, that we test_add_attr2 would fail, if is executed prior test_add_attr1. If the execution order of the test methods is strict, we can rely on a pytest-xdist feature to distribute all test cases to the nodes on per file basis, which basically circumvents this problem. Generally we should write tests such, that they have no interdependence.
One example where this interdependence occurs is weldx.tests.test_transformation.TestCoordinateSystemManager.test_add_coordinate_system.
This test method is parameterized to add different coordinate systems to the manager and it is being checked if the previous additions are still valid. The methods act on a single (static) instance of the CSM, which grows for every (parameterized-)test executed.

In my opinion we should avoid having static data as much as possible, since it is easy to cause side-effects, which therefore affects the outcome of the tests. Only the side-effect of the actual property of interest should be triggered and tested. What would happen if another programmer adds a test acting on the same static instance and affects the other tests in a non intended way. These kind of problems are hard to debug and should be avoided.
When the same data is needed, we should consider factory functions like pytest.fixtures or unittest.TestCase.setUp to create a clean and defined environment for the actual test case execution.

**Comment by vhirtham** [comment]
Agreed. The mentioned tests are leftovers from starting with parametrized tests. The problem we had (and are still facing) was that writing good tests in the sense of readability, understandability, and completeness can be quite challenging and time-consuming. In this particular case (`weldx.tests.test_transformation.TestCoordinateSystemManager.test_add_coordinate_system`), the setup of the CSM  would have taken multiple lines per test case and using fixtures that depend on multiple parameters makes it necessary to jump in the code when trying to understand what the test is actually doing. However, this didn't consider parallelism back then (at least not at a test case level). 

I came to the conclusion that it is often better to write multiple tests with repeating code sections instead of one heavily parametrized one if that keeps each test readable (no multi-line sets of test parameters). So we might want to split the problematic tests into multiple ones when refactoring them to be self-contained.
