### ISSUE TITLE
update weldx extension implementation for ASDF 2.8

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#370]
check and update our extension definition and implementation against new ASDF 2.8 API

https://asdf.readthedocs.io/en/latest/asdf/extending/extensions.html

same for quality standards (cookiecutter template)

**Comment by vhirtham** [comment]
I want to gather the things that we need to adjust for a full transition to ASDF 2.8.

From reading the documentation I figured the following necessary changes so far:

## Schemas
- ids and tags need to be renamed (see #368)
- tags are removed from the schema. The mapping is provided by the extension (see: [ASDF Extension doc](https://asdf.readthedocs.io/en/latest/asdf/extending/extensions.html) - additional tags -> `TagDefinition`)

## Tags
- use new `Converter` class (while refactoring, consider move import of the class to `from_tree`, but we should discuss it since I am not sure if it makes that much sense for us)

---

I would suggest, that we merge the quality standards branch asap. Afterwards, I will create a new asdf 2.8 branch + PR where we can implement all the changes (including #382). Most of the stuff is just simple renaming and perfect for situations where you need a break from complex thinking exercises. 😄 So a perfect ☕ task.

**Comment by CagtayFabry** [comment]
I will have to look into the `Converter` class more but we have to think about how to carry over some aspects of the current implementation, specifically the tasks now covered by inheriting from `WeldxExtension` (maybe create a `WeldxConverter`?)
- registering the tags and schemas automatically (not sure if needed)
- updating the `to_tree` method to remove `None` fields for serialization

**Comment by CagtayFabry** [comment]
I guess we should finish the current (working) implementation of the Quality Standards for `0.4` and maybe do a bigger clean up and asdf 2.8+ interface adaptation for `0.5`

we should probably also ask over at asdf when the old interfaces will be deprecated

**Comment by vhirtham** [comment]
> I guess we should finish the current (working) implementation of the Quality Standards for `0.4` and maybe do a bigger clean up and asdf 2.8+ interface adaptation for `0.5`
> 
> we should probably also ask over at asdf when the old interfaces will be deprecated

Agreed
