### ISSUE TITLE
use basic weldx file examples in documentation

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#400]
some of our tutorials reuse code to generate the same basic layout (like a default V-Groove workpiece, a basic CSM instance etc.)
I think we should provide and load these basic examples as files that get created (and explained) in their own tutorials to slim down the feature tutorials to cover their essential topics

**Comment by CagtayFabry** [comment]
This would also help create more well documented example files that we can use for workshops etc.

**Comment by marscher** [comment]
This is a good idea. There is only one draw back from this. The notebooks are not self contained any more but have an execution order dependency. Or are you saying we should store the weldx files containing groove, csm etc. within the repo?

**Comment by CagtayFabry** [comment]
I would suggest starting with simply adding the files to the repo, they should not be large files anyway.

The tutorials don't need to recreate the exact files, but let's say we load workpiece information form a file, we would link to the tutorial that handles these parts and creates similar outputs. We should still store the code for creating the files in the repo as well though.

**Comment by vhirtham** [comment]
> We should still store the code for creating the files in the repo as well though.

If we store the code for the file creation anyways, why not call it at the start of each tutorial? It can be placed in a hidden cell if we do not want to bother the reader with it. This way, we avoid bloating the repository size and do not need to recreate the files whenever we touch the asdf serialization. The second point is quite important as we can see with both conference notebooks. @AndreasPittner couldn't run the one from the last conference with the current weldx `master` due to a validation error. The CI pipelines would catch that, but my point is that the files get outdated rather quickly in the current state and some kB that get updated every now and then will add up over time and increase the repository size.

**Comment by CagtayFabry** [comment]
sure but it would also be nice to have a few examples files ready to go and look into directly in the repo imo

**Comment by vhirtham** [comment]
> sure but it would also be nice to have a few examples files ready to go and look into directly in the repo imo

I don't know. I don't see the purpose/benefit here. Maybe we should discuss this when we talk about the documentation.

**Comment by marscher** [comment]
I would vote for having a separate tutorials repository, which then includes these files. We can then include it as a git submodule.
I also like the idea of having hidden cells generating the files.

Was there a discussion already, which I missed? Whats the status on this one?

**Comment by vhirtham** [comment]
> I would vote for having a separate tutorials repository, which then includes these files. We can then include it as a git submodule.
> I also like the idea of having hidden cells generating the files.
> 
> Was there a discussion already, which I missed? Whats the status on this one?

We had some verbal discussions regarding this. The current plan is to write everything based on the IW presentation file and think about the file for the WelDX repo later. The only difference should be the actual data inside those files. @CagtayFabry suggested, that we can use a reduced set of actual measurement data. The `weldx` file will still be generated on the fly (IIRC). The measurement data will be stored in a different format so that we can demonstrate in one of the tutorials how to transfer data to a `weldx` file.

Maybe we can talk about this tomorrow in the Jour Fixe
