### ISSUE TITLE
move k3d functions to weldx-widgets

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#513]
to lighten the dependency load of our core `weldx` package a little I think it would make sense to migrate some of the advanced features over to the [weldx-widgets](https://github.com/BAMWelDX/weldx-widgets) package

Some things to consider/discuss:
- can we keep some of the convenience functionality, like calling `*CSM.plot()` and redirecting the call to the `weldx-widgets` package if that is installed?
- how to version the `weldx-widgets` package? I suggest using the same version numbers as the weldx package and pinning that requirement?

**Comment by marscher** [comment]
I agree that we should do this split. Preserving the existence of easy plotting routine should be kept.

I'd vote against a strict version coupling and use semantic versioning whenever possible. E.g. there is a breaking change in the CSM api, which does not allow the visualization routine to work properly, one should increase the `weldx-widgets` major and require this in weldx. The requirement will have to be made during import time of course. Otherwise we would still drag in lots of dependencies we would not need for basic file io.

**Comment by marscher** [comment]
Actually we should consider the same thing for matplotlib dependent features.

**Comment by CagtayFabry** [comment]
sounds good, I suggest to start with k3d first and move to other features (like mpl) later

**Comment by CagtayFabry** [comment]
see #636
