### ISSUE TITLE
`k3d` line width for traces

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#608]
I tried changing the display width of traces in our k3d plots by changing the default value here:

https://github.com/BAMWelDX/weldx/blob/69ed4dbc87e8fd01a0125732b2c8012aea7446c4/weldx/visualization/k3d_impl.py#L155-L160

unfortunately, no effect.
The basic k3d example works:
```python
import numpy as np
import k3d

plot = k3d.plot(name='Wiener process')
N = 1000
traj = np.cumsum(np.random.randn(N, 3).astype(np.float32), axis=0)
plt_line = k3d.line(traj, shader='mesh', width=0.5)
plt_line2 = k3d.line([traj[0], traj[-1]], shader='mesh', width=3.5, color=0xff0000)
plot += plt_line
plot += plt_line2
plot.display()
```

any ideas?

**Comment by vhirtham** [comment]
This is because the WelDX implementation uses the `"simple"` shader. If you change it to `"mesh"` like in your example, everything works. The simple shader just renders a line with a fixed pixel width. This should be generally preferable because otherwise, we get the same problems as we have with the vectors -> thickness depends on the axis scaling.
