### ISSUE TITLE
add merge/compose function to CSM

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#68]
add functionality to merge/add two (or more) CSM instances based on node names. Basically append a graph to an existing CSM instance, probably using  [networkx.algorithms.operators.binary.compose](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.operators.binary.compose.html) .

https://stackoverflow.com/a/32697415/11242411

**Comment by vhirtham** [comment]
The current graph structure of the CSM is a tree and I am not sure if anything else makes much sense here. So if I am not mistaken, joining 2 of them would mean that there can only be one common node in both CSMs. Also, to avoid problems during deserialization, we might need to enable arbitrary inclusion orders for coordinate systems (add systems without the need to have a connection to the root, at least when they are added).

**Comment by CagtayFabry** [comment]
agreed, normally there should only ever exist a single common node when merging. We could check for this before composing.
I think arbitrary inclusion orders would also simplify some workflows when setting up the CSM instance.

**Comment by vhirtham** [comment]
**Benefits of this functionality**
- Subsystems can be built individually. For example, the whole setup of cameras, scanners, and the torch at the flange or a specific set of coordinate systems in the specimen coordinate system (thermoelements and other sensors). This makes it easy to predefine specific setups and combine them at will
- This would give some flexibility regarding the order of how the full coordinate system hierarchy is built without the need to drop the strict order requirements when adding coordinate systems to a CSM instance. Dropping the requirement that the reference system of a new system must already be added would have made things a little bit complicated because the CSM needs to assure somehow that there are no disconnected substructures once the "building process" is over. 


**Internal changes to support this**
- explicitly store the root system Name
- get_parent_system_name (should get a more appropriate name) finds the (shortest) path to the root and returns the name of its corresponding neighbor on this path
- During asdf serialization, "demerge" the systems and store the subsystems --- this might require storing a "merge history" and naming the individual CSM instances
