### ISSUE TITLE
store external file contents

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#91]
support including external files into weldx files
- filetype and other metadata
- provide explicit hash for fast checks?

**Comment by CagtayFabry** [comment]
we should discuss which metadata to store in the ASDF tree, probably starting with https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat 

for the schema I suggest the following 
- file_uri (absolute)
- filename
- suffix (may be redundant)

**Comment by vhirtham** [comment]
To keep the discussion in one place, here your suggestion from the pull request:

~~~ yaml
properties:
  file_uri:
    type: string
    pattern: "^file://"
    description: The absolute file URI.
  filename:
    type: string
    pattern: # some pattern to validate filenames
    description: original filename
  suffix:
    type: string
    description: The filetype/suffix.
    # this would be a good place to put restrictions in other schemas or quality standards
  created:
    tag: "tag:weldx.bam.de:weldx/time/timestamp-1.0.0"
  modified:
    tag: "tag:weldx.bam.de:weldx/time/timestamp-1.0.0"
  # some other file metadata
  content:
    tag: tag:stsci.edu:asdf/core/ndarray-1.0.0
  content_hash:
    type: object
    properties:
      algo:
        type: string
        enum: [MD5, SHA-256, SHA-512] # probably look up some codes
      value:
        type: string
~~~

I am not sure about the `file_uri`.  Maybe I am getting confused again by URI and URL but what is its purpose? If we want to define directory structures of multiple related files I'd suggest that we create an extra `file_structure` or `file_system` schema for that like we did with the `CoordinateSystemManager` and `LocalCoordinateSystem`s. 

I am also not sure about the `suffix`. It is either redundant or requires us to apply another operation on the name that doesn't provide any additional information.

I would consider `created` and `modified` as metadata. I am not even sure if we can restore the file with those timestamps applied to it. Well technically it should be possible since archiving tools can do that too, but I don't know if that might get ugly.

The `hash` is something we should store as extra validation. Just need to perform some research on our options.
